- name: ensure common-packages are at the latest version
  yum: name={{item}} state=latest
  with_items:
    - gcc
    - make
    - git
    - readline-devel
    - openssl-devel
    - zlib-devel
    - sqlite-devel
