- name: ensure rbenv is installed
  sudo: no
  git: repo=git://github.com/sstephenson/rbenv.git
       dest=~/.rbenv
       version=master
  tags: rbenv

- name: ensure .rbenv setting is in .bashrc
  sudo: no
  lineinfile: dest=~/.bashrc {{ item }}
  with_items:
    - regexp='.rbenv/bin:' line='export PATH="$HOME/.rbenv/bin:$PATH"'
    - regexp='rbenv init -' line='eval "$(rbenv init -)"'
  tags: rbenv

- name: ensure ruby-build is installed
  sudo: no
  git: repo=git://github.com/sstephenson/ruby-build.git
       dest=~/.rbenv/plugins/ruby-build
       version=master
  tags: rbenv

- name: check current ruby version
  sudo: no
  shell: rbenv version | cut -f 1 -d ' '
  register: current_ruby_version
  tags: rbenv

- name: ensure ruby is installed
  sudo: no
  shell: rbenv {{ item }} {{ ruby_version }}
  with_items:
    - install
    - global
  when: current_ruby_version.stdout != ruby_version
  tags: rbenv

- name: ensure bundler is installed
  sudo: no
  gem: name=bundler state=latest
  tags: rbenv
