- name: ensure mysql-shared-compat is installed
  yum: name='ftp://ftp.iij.ad.jp/pub/db/mysql/Downloads/MySQL-5.6/MySQL-shared-compat-5.6.13-1.el6.x86_64.rpm' state=present
  tags: mysql

- name: ensure mysql-shared is installed
  yum: name='ftp://ftp.iij.ad.jp/pub/db/mysql/Downloads/MySQL-5.6/MySQL-shared-5.6.13-1.el6.x86_64.rpm' state=present
  tags: mysql

- name: ensure mysql-devel is installed
  yum: name='ftp://ftp.iij.ad.jp/pub/db/mysql/Downloads/MySQL-5.6/MySQL-devel-5.6.13-1.el6.x86_64.rpm' state=present
  tags: mysql

- name: ensure mysql-client is installed
  yum: name='ftp://ftp.iij.ad.jp/pub/db/mysql/Downloads/MySQL-5.6/MySQL-client-5.6.13-1.el6.x86_64.rpm' state=present
  tags: mysql
