- name: ensure rails_app directory is created
  file: path=/var/www/${rails_app_name} state=directory mode=0775 owner=${user} group=nginx
  tags: rails

- name: ensure rails_app is configured
  template: src=rails_app.conf.j2 dest=/etc/nginx/conf.d/${rails_app_name}.conf owner=root group=root
  notify:
    - reload nginx
  tags: rails

- name: ensure database is present
  mysql_db: db=${dbname} state=present
  tags: mysql

- name: ensure database user is present
  mysql_user: name=${dbuser} password=${dbpassword} priv=${dbname}.*:ALL state=present host=${item}
  with_items:
    - localhost
    - '%'
  tags: mysql
